GET http://localhost:3000/api/test

###

GET http://localhost:3000/api/users

###REEGISTRO###
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "Admin",
    "email": "Admin@gmail.com",
    "password":"chorizo"
}

###LOGIN###
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{

    "email": "Ignacio30@gmail.com",
    "password":"chorizo"
}


###EDITAR DATOS USUARIO###
###


PUT http://localhost:3000/api/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgwOTMxODMwLCJleHAiOjE3ODEwMTgyMzB9.7w3AwtJB-6FSMYVIF2As0a_sHZaGkFLoZskp1B-1EgY

{
    "username": "Ignacio30",
    "email": "Ignacio30@gmail.com",
    "location": "Valencia",
    "avatar_url": null
}

### reportar un usuario
POST http://localhost:3000/api/users/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MTU0OTAzMSwiZXhwIjoxNzgxNTUyNjMxfQ.9a5vgYtxVbkQczVRJO35ANMIPv0uDi-qyVYeLVoNMZE
Content-Type: application/json

{
    "type": "Usuario",
    "reported_user_id": 5,
    "reason": "me intenta estafar por el chat"
}

### reportar un article
POST http://localhost:3000/api/users/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2LCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MTU0OTAzMSwiZXhwIjoxNzgxNTUyNjMxfQ.9a5vgYtxVbkQczVRJO35ANMIPv0uDi-qyVYeLVoNMZE
Content-Type: application/json

{
    "type": "Articulo",
    "article_id": 7,
    "reason": "llega roto"
}






















### pRUEBA DE SI RENDER FUNCIONA
GET https://proyecto-final-node-5pwe.onrender.com/api/test

###REEGISTRO VIA RRENDER###
###
###REEGISTRO VIA RRENDER###

###REEGISTRO VIA RRENDER###
@baseUrl = https://proyecto-final-node-5pwe.onrender.com

### Registro
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
    "username": "Render_Prueba",
    "email": "Render_prueba1@gmail.com",
    "password": "chorizo"
}

### Login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
    "email": "Render_editado@email.com",
    "password": "chorizo"
}

### Ver perfil

PUT {{baseUrl}}/api/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE4LCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MDgzMDc5MSwiZXhwIjoxNzgwOTE3MTkxfQ.vnHaKgUYbAJycsYmGlkCp7WtElMJB9amA7PTk9Z1uxc

{
    "username": "Render_editado",
    "email": "Render_editado@email.com",
    "location": "Madrid",
    "avatar_url": null
}

