GET http://localhost:3000/api/test

###

GET http://localhost:3000/api/users

###REEGISTRO###
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "Julio Iglesias",
    "email": "Julioiglesias@gmail.com",
    "password":"megustaelvino"
}

###LOGIN###
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{

    "email": "Julioiglesias@gmail.com",
    "password":"megustaelvino"
}


###EDITAR DATOS USUARIO###
###


PUT http://localhost:3000/api/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJpYXQiOjE3ODAzMzE0NjJ9.Qr7QknqRpT5O4lkr4yEMUgEcMfMhvNuWSGamjeTC3FQ

{
    "username": "carlos_nuevo",
    "email": "carlo33@email.com",
    "location": "Valencia",
    "avatar_url": null
}
