

# reportar articulo
POST http://localhost:3000/api/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MjQyMTIwMywiZXhwIjoxNzgyNDI0ODAzfQ.oYQCZn2Un5yhdaWnC_0D_0z8H1jBIXwixXVsWIniWu0
Content-Type: application/json

{
    "type": "Articulo",
    "article_id": 2,
    "reason": "Las zapatillas llegaron rotas"
}

# reportar usuario
###
POST http://localhost:3000/api/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUyLCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MjQyMTIwMywiZXhwIjoxNzgyNDI0ODAzfQ.oYQCZn2Un5yhdaWnC_0D_0z8H1jBIXwixXVsWIniWu0
Content-Type: application/json 

{
 
    "type": "Articulo",
    "article_id": 18,

    "reason": "me quedan pequeñas"
}


