# reportar usuario
###
POST http://localhost:3000/api/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUxLCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MjI5NjI0MywiZXhwIjoxNzgyMjk5ODQzfQ.Ue2ebvTN0lJQ2QqOslLt68FZHa-ZMbEiRQ7qttsC-9w
Content-Type: application/json

{
    "type": "Usuario",
    "reported_user_id": 5,
    "reason": "me intenta estafar por el chat"
}

# reportar articulo
###
POST http://localhost:3000/api/reports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUxLCJyb2xlIjoiVXN1YXJpbyIsImlhdCI6MTc4MjI5NjI0MywiZXhwIjoxNzgyMjk5ODQzfQ.Ue2ebvTN0lJQ2QqOslLt68FZHa-ZMbEiRQ7qttsC-9w
Content-Type: application/json

{
  "type": "Articulo",
  "article_id": 10,
  "reason": "El precio parece muy bajo, podría ser fraudulento"
}

# Obtener reportes pendientes de artículos (Moderador/Administrador)
###
GET http://localhost:3000/api/reports/pending/articles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI

# Obtener detalle reporte pendiente del artículo (Moderador/Administrador)
###
GET http://localhost:3000/api/reports/pending/articles/29
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI

# Obtener reportes pendientes de usuarios (Moderador/Administrador)
###
GET http://localhost:3000/api/reports/pending/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI

# Obtener detalle reporte pendiente del artículo (Moderador/Administrador)
###
GET http://localhost:3000/api/reports/pending/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI

# Resolucíon del reporte de un artículo (Moderador/Administrador)
###
PUT http://localhost:3000/api/reports/resolution/29
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI
Content-Type: application/json

{
    "action": "reject",
    "moderator_note": "El artículo cumple las condiciones de la plataforma"
}

# Obtener el historial de reportes resueltos (Moderador/Administrador)
###
GET http://localhost:3000/api/reports/history
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMxLCJyb2xlIjoiTW9kZXJhZG9yIiwiaWF0IjoxNzgyMjk4NzkwLCJleHAiOjE3ODIzMDIzOTB9.wMBKfr1Du9R6a19-smd_F4r8FJZ1TZwm_4oRBMIPBHI
